fix(ts) adjust syntax so TSC doesn't complain
Emitting declarations generated these errors:

~~~~
modules/transcription/audioRecorder.js:3:1 - error TS9005: Declaration emit for this file requires using private name 'TrackRecorder'. An explicit type annotation may unblock declaration emit.

3 const RecordingResult = require('./recordingResult');
  ~~~~~

modules/transcription/recordingResult.js:13:1 - error TS9005: Declaration emit for this file requires using private name 'RecordingResult'. An explicit type annotation may unblock declaration emit.

13 const RecordingResult = function(blob, name, startTime, wordArray) {
   ~~~~~

modules/transcription/transcriber.js:1:1 - error TS9006: Declaration emit for this file requires using private name 'SphinxService' from module '"/Users/saghul/work/jitsi/lib-jitsi-meet/modules/transcription/transcriptionServices/SphinxTranscriptionService"'. An explicit type annotation may unblock declaration emit.

1 const AudioRecorder = require('./audioRecorder');
  ~~~~~

modules/transcription/word.js:7:1 - error TS9005: Declaration emit for this file requires using private name 'Word'. An explicit type annotation may unblock declaration emit.

7 const Word = function(word, begin, end) {
  ~~~~~

Found 4 errors.
~~~~